[book]
authors = ["Demian"]
language = "zh"
multilingual = false
src = "src"
title = "promised land"

[preprocessor.katex]
after = ["links"]
macros = "macros.txt" # ref from https://github.com/Trapdoor-Tech/Halo2-Book/blob/master/book/macros.txt

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[TOC]"
max-level = 4


# This will run mdbook-gettext on the source after things like {{ #include }} has been executed
[preprocessor.gettext]
after = ["links"]

# To automatically reload the book when you change the po/xx.po file
[build]
extra-watch-dirs = ["po"]